In [1]:
import pandas as pd
from sklearn.cluster import KMeans

2018

In [2]:
df = pd.read_excel('2018.xlsx')
df

,Provinsi,Jumlah Kejahatan (Crime Total) yang dilaporkan Menurut Polda,crime rate,asusila,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap ketertiban umum,kejahatan terhadap fisik
0,ACEH,8885,171,311,27,38,3238,219,1544,1338,9,1764
1,SUMATERA UTARA,39867,280,224,92,19,12361,908,5904,5297,0,5633
2,SUMATERA BARAT,13205,248,343,14,158,7511,463,592,1881,360,2371
3,RIAU,6869,103,97,28,11,2389,263,1173,966,2,791
4,JAMBI,9531,271,113,24,225,3913,274,712,1865,312,1015
5,SUMATERA SELATAN,13205,256,220,147,116,4557,1064,1768,2376,282,2043
6,BENGKULU,4867,252,94,37,5,2050,203,192,728,35,395
7,LAMPUNG,11089,134,163,50,8,2387,774,1744,1444,1,401
8,KEP BANGKA BELITUNG,1931,135,43,9,38,759,25,224,190,0,95
9,KEP RIAU,3673,176,131,6,5,1465,175,400,703,0,641
10,DKI JAKARTA,34767,138,176,76,44,5624,635,7214,6169,227,1995
11,JAWA BARAT,25183,65,349,89,152,10402,1003,1090,4793,398,2547
12,JAWA TENGAH,12033,35,270,30,222,4621,256,1243,1540,293,730
13,DI YOGYAKARTA,7251,193,38,1,24,1760,117,290,808,76,361
14,JAWA TIMUR,34598,88,258,60,210,6564,627,3405,3639,133,2442
15,BANTEN,3692,55,92,31,111,1585,128,389,625,0,351
16,BALI,3589,85,77,11,22,1245,85,665,451,1,582
17,NUSA TENGGARA BARAT,8132,164,64,7,76,2082,403,227,720,2,484
18,NUSA TENGGARA TIMUR,6729,127,215,34,40,2117,125,2,766,892,2491
19,KALIMANTAN BARAT,6020,122,226,13,104,2281,180,490,685,1,254
20,KALIMANTAN TENGAH,2699,104,94,30,2,641,132,474,254,0,222
21,KALIMANTAN SELATAN,6578,160,68,30,0,1540,475,1211,554,0,387
22,KALIMANTAN TIMUR,9149,214,148,20,3,2492,232,2928,876,178,897
23,KALIMANTAN UTARA,10125,170,167,34,79,3243,324,1073,1441,123,838
24,SULAWESI UTARA,7981,324,384,103,25,1557,140,111,1275,8,944
25,SULAWESI TENGAH,10240,345,245,15,24,5756,214,259,1339,4,1958
26,SULAWESI SELATAN,21616,256,322,65,405,8093,1137,717,4089,3,5540
27,SULAWESI TENGGARA,2866,110,142,17,29,983,29,65,231,1,924
28,GORONTALO,3099,265,166,10,46,1016,8,38,545,15,1445
29,SULAWESI BARAT,1841,146,62,15,33,650,36,120,310,0,564
30,MALUKU,3086,177,123,7,142,772,7,73,323,298,821
31,MALUKU UTARA,789,65,155,7,14,118,16,63,47,4,184
32,PAPUA BARAT,2284,146,34,6,102,945,92,41,260,143,450
33,PAPUA,6785,208,66,37,183,3568,247,41,498,406,961

In [3]:
df = pd.read_excel('2018.xlsx')
provinsi = df['Provinsi']
df = df.drop(columns=[
    'Provinsi','Jumlah Kejahatan (Crime Total) yang dilaporkan Menurut Polda',
    'crime rate',
    'kejahatan terhadap ketertiban umum'
    ])

In [81]:
df.isnull().sum()n

Provinsi                                         0
asusila                                          0
kejahatan terhadap nyawa                         0
kejahatan terhadap kemerdekaan                   0
kejahatan terhdap hak milik                      0
kejahatan terhadap hak milik dengan kekerasan    0
kejahatan terkait narkotika                      0
kejahatan penipuan, penggelapan, dan korupsi     0
kejahatan terhadap fisik                         0
Tingkat Kriminalitas                             0
dtype: int64

Modeling (K-Means)

In [5]:
kmeans = KMeans(n_clusters=3,random_state=144)
kmeans.fit(df)

c:\Users\shiro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=144)

In [6]:
labels = kmeans.labels_

In [7]:
X = df[['asusila', 'kejahatan terhadap nyawa', 'kejahatan terhadap kemerdekaan', 'kejahatan terhdap hak milik', 'kejahatan terhadap hak milik dengan kekerasan', 'kejahatan terkait narkotika', 'kejahatan penipuan, penggelapan, dan korupsi', 'kejahatan terhadap fisik']]

In [8]:
labels

array([0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0])

In [9]:
from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(X,labels)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.567849109692876

In [10]:
df['cluster'] = labels
df.head()

,asusila,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik,cluster
0,311,27,38,3238,219,1544,1338,1764,0
1,224,92,19,12361,908,5904,5297,5633,1
2,343,14,158,7511,463,592,1881,2371,2
3,97,28,11,2389,263,1173,966,791,0
4,113,24,225,3913,274,712,1865,1015,0

Cluster profiling

In [11]:
df_0 = df.loc[df['cluster']==0]
df_1 = df.loc[df['cluster']==1]
df_2 = df.loc[df['cluster']==2]

0

In [12]:
df_0.describe().mean()

asusila                                           127.548928
kejahatan terhadap nyawa                           29.566369
kejahatan terhadap kemerdekaan                     65.343013
kejahatan terhdap hak milik                      1604.654938
kejahatan terhadap hak milik dengan kekerasan     208.242442
kejahatan terkait narkotika                       707.274136
kejahatan penipuan, penggelapan, dan korupsi      644.526651
kejahatan terhadap fisik                          723.439569
cluster                                             3.250000
dtype: float64

In [13]:
df_1.describe().mean()

asusila                                           154.492641
kejahatan terhadap nyawa                           64.664214
kejahatan terhadap kemerdekaan                     26.084709
kejahatan terhdap hak milik                      7340.097298
kejahatan terhadap hak milik dengan kekerasan     603.005019
kejahatan terkait narkotika                      5035.288735
kejahatan penipuan, penggelapan, dan korupsi     4377.074639
kejahatan terhadap fisik                         3182.306809
cluster                                             1.000000
dtype: float64

In [14]:
df_2.describe().mean()

asusila                                           224.468453
kejahatan terhadap nyawa                           56.700223
kejahatan terhadap kemerdekaan                    152.115806
kejahatan terhdap hak milik                      5635.650801
kejahatan terhadap hak milik dengan kekerasan     606.186071
kejahatan terkait narkotika                      1156.370793
kejahatan penipuan, penggelapan, dan korupsi     2437.906457
kejahatan terhadap fisik                         2340.862768
cluster                                             2.250000
dtype: float64

In [15]:
df_0.describe().mean().mean()

457.0940050870474

In [16]:
df_1.describe().mean().mean()

2309.3348959187365

In [17]:
df_2.describe().mean().mean()

1401.390152462247

0 = Rendah

1 = Tinggi

2 = Sedang

In [18]:
tingkat_kriminalitas_bin=[]
for i in df['cluster']:
    if i == 0 :
        tingkat_kriminalitas_bin.append('Rendah')
    elif i == 1 :
        tingkat_kriminalitas_bin.append('Tinggi')
    else:
        tingkat_kriminalitas_bin.append('Sedang')

In [19]:
df['cluster'] = tingkat_kriminalitas_bin
df = df.rename(columns={'cluster': 'Tingkat Kriminalitas'})

df.insert(0, 'Provinsi',provinsi)
df

,Provinsi,asusila,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik,Tingkat Kriminalitas
0,ACEH,311,27,38,3238,219,1544,1338,1764,Rendah
1,SUMATERA UTARA,224,92,19,12361,908,5904,5297,5633,Tinggi
2,SUMATERA BARAT,343,14,158,7511,463,592,1881,2371,Sedang
3,RIAU,97,28,11,2389,263,1173,966,791,Rendah
4,JAMBI,113,24,225,3913,274,712,1865,1015,Rendah
5,SUMATERA SELATAN,220,147,116,4557,1064,1768,2376,2043,Sedang
6,BENGKULU,94,37,5,2050,203,192,728,395,Rendah
7,LAMPUNG,163,50,8,2387,774,1744,1444,401,Rendah
8,KEP BANGKA BELITUNG,43,9,38,759,25,224,190,95,Rendah
9,KEP RIAU,131,6,5,1465,175,400,703,641,Rendah
10,DKI JAKARTA,176,76,44,5624,635,7214,6169,1995,Tinggi
11,JAWA BARAT,349,89,152,10402,1003,1090,4793,2547,Sedang
12,JAWA TENGAH,270,30,222,4621,256,1243,1540,730,Rendah
13,DI YOGYAKARTA,38,1,24,1760,117,290,808,361,Rendah
14,JAWA TIMUR,258,60,210,6564,627,3405,3639,2442,Sedang
15,BANTEN,92,31,111,1585,128,389,625,351,Rendah
16,BALI,77,11,22,1245,85,665,451,582,Rendah
17,NUSA TENGGARA BARAT,64,7,76,2082,403,227,720,484,Rendah
18,NUSA TENGGARA TIMUR,215,34,40,2117,125,2,766,2491,Rendah
19,KALIMANTAN BARAT,226,13,104,2281,180,490,685,254,Rendah
20,KALIMANTAN TENGAH,94,30,2,641,132,474,254,222,Rendah
21,KALIMANTAN SELATAN,68,30,0,1540,475,1211,554,387,Rendah
22,KALIMANTAN TIMUR,148,20,3,2492,232,2928,876,897,Rendah
23,KALIMANTAN UTARA,167,34,79,3243,324,1073,1441,838,Rendah
24,SULAWESI UTARA,384,103,25,1557,140,111,1275,944,Rendah
25,SULAWESI TENGAH,245,15,24,5756,214,259,1339,1958,Sedang
26,SULAWESI SELATAN,322,65,405,8093,1137,717,4089,5540,Sedang
27,SULAWESI TENGGARA,142,17,29,983,29,65,231,924,Rendah
28,GORONTALO,166,10,46,1016,8,38,545,1445,Rendah
29,SULAWESI BARAT,62,15,33,650,36,120,310,564,Rendah
30,MALUKU,123,7,142,772,7,73,323,821,Rendah
31,MALUKU UTARA,155,7,14,118,16,63,47,184,Rendah
32,PAPUA BARAT,34,6,102,945,92,41,260,450,Rendah
33,PAPUA,66,37,183,3568,247,41,498,961,Rendah

In [20]:
df.to_excel('2018_FINAL.xlsx',index=False)

2019

In [21]:
df_2019 = pd.read_excel('2019.xlsx')
provinsi = df_2019['Provinsi']

In [22]:
df_2019=df_2019.drop(columns=['Provinsi','Crime_Total','Crime_Rate'])

In [23]:
kmeans = KMeans(n_clusters=3,random_state=144)
kmeans.fit(df_2019)

c:\Users\shiro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=144)

In [24]:
labels = kmeans.labels_

In [25]:
from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(df_2019,labels)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.5725830061673394

In [26]:
df_2019['cluster'] = labels
df_2019.head()

,Kesusilaan,Nyawa,Fisik_Badan,Kemerdekaan,HMB_Kekerasan,HMB_Tanpa_Kekerasan,Narkotika,Penipuan,cluster
0,262,22,1475,41,156,2959,1625,1471,1
1,321,107,5240,88,702,10818,6262,4680,2
2,392,14,2153,132,387,7230,806,1847,0
3,98,30,852,16,301,2333,1717,1060,1
4,90,23,571,53,119,2283,439,959,1

In [27]:
df_2019_0 = df_2019.loc[df_2019['cluster']==0]
df_2019_1 = df_2019.loc[df_2019['cluster']==1]
df_2019_2 = df_2019.loc[df_2019['cluster']==2]

0

In [28]:
df_2019_0.describe().mean()

Kesusilaan              250.671410
Nyawa                    35.207093
Fisik_Badan            2023.395810
Kemerdekaan             139.086199
HMB_Kekerasan           283.949661
HMB_Tanpa_Kekerasan    5146.632557
Narkotika              1040.769837
Penipuan               2447.422323
cluster                   0.625000
dtype: float64

In [29]:
df_2019_1.describe().mean()

Kesusilaan              105.682099
Nyawa                    29.937703
Fisik_Badan             686.983041
Kemerdekaan              67.630049
HMB_Kekerasan           176.310470
HMB_Tanpa_Kekerasan    1431.882191
Narkotika               673.750020
Penipuan                658.235536
cluster                   4.125000
dtype: float64

In [30]:
df_2019_2.describe().mean()

Kesusilaan              187.976844
Nyawa                    71.328427
Fisik_Badan            3003.347916
Kemerdekaan              51.919417
HMB_Kekerasan           441.626339
HMB_Tanpa_Kekerasan    6259.659221
Narkotika              5833.441617
Penipuan               3902.276542
cluster                   1.750000
dtype: float64

In [31]:
df_2019_0.describe().mean().mean()

1263.084432172034

In [32]:
df_2019_1.describe().mean().mean()

426.0595677522993

In [33]:
df_2019_2.describe().mean().mean()

2194.8140360218986

0 = Sedang

1 = Rendah 

2 = Tinggi

In [34]:
tingkat_kriminalitas_bin=[]
for i in df_2019['cluster']:
    if i == 0 :
        tingkat_kriminalitas_bin.append('Sedang')
    elif i == 1 :
        tingkat_kriminalitas_bin.append('Rendah')
    else:
        tingkat_kriminalitas_bin.append('Tinggi')

In [35]:
df_2019['cluster'] = tingkat_kriminalitas_bin
df_2019 = df_2019.rename(columns={'cluster': 'Tingkat Kriminalitas'})

df_2019.insert(0, 'Provinsi',provinsi)
df_2019

,Provinsi,Kesusilaan,Nyawa,Fisik_Badan,Kemerdekaan,HMB_Kekerasan,HMB_Tanpa_Kekerasan,Narkotika,Penipuan,Tingkat Kriminalitas
0,ACEH,262,22,1475,41,156,2959,1625,1471,Rendah
1,SUMATERA UTARA,321,107,5240,88,702,10818,6262,4680,Tinggi
2,SUMATERA BARAT,392,14,2153,132,387,7230,806,1847,Sedang
3,RIAU,98,30,852,16,301,2333,1717,1060,Rendah
4,JAMBI,90,23,571,53,119,2283,439,959,Rendah
5,SUMATERA SELATAN,175,111,1753,132,694,3812,2001,2108,Rendah
6,BENGKULU,77,26,424,6,116,1125,165,395,Rendah
7,LAMPUNG,65,11,309,7,499,1882,2511,1135,Rendah
8,KEP. BANGKA BELITUNG,52,9,96,33,38,666,377,143,Rendah
9,KEP. RIAU,125,6,586,2,109,1462,410,649,Rendah
10,DKI JAKARTA,136,75,2006,38,405,4349,8715,5526,Tinggi
11,JAWA BARAT,512,35,1646,33,365,4841,1604,4070,Sedang
12,JAWA TENGAH,226,34,631,199,203,3727,991,1300,Rendah
13,DI YOGYAKARTA,49,2,334,14,138,1643,250,1111,Rendah
14,JAWA TIMUR,292,72,2345,161,668,7090,2712,4212,Sedang
15,BANTEN,88,5,379,136,128,1566,339,514,Rendah
16,BALI,99,10,547,29,63,1233,746,486,Rendah
17,NUSA TENGGARA BARAT,36,3,380,54,261,1459,193,589,Rendah
18,NUSA TENGGARA TIMUR,215,45,2367,78,66,2104,6,818,Rendah
19,KALIMANTAN BARAT,120,26,251,129,98,2305,720,628,Rendah
20,KALIMANTAN TENGAH,87,14,231,3,111,908,640,251,Rendah
21,KALIMANTAN SELATAN,59,43,379,2,500,1437,1650,392,Rendah
22,KALIMANTAN TIMUR,99,16,552,0,162,1532,2108,669,Rendah
23,KALIMANTAN UTARA,26,4,39,1,4,158,77,50,Rendah
24,SULAWESI UTARA,321,68,2375,51,99,2474,888,1539,Rendah
25,SULAWESI TENGAH,175,13,1573,15,247,5059,311,1305,Sedang
26,SULAWESI SELATAN,175,72,4700,440,28,8728,707,3747,Sedang
27,SULAWESI TENGGARA,90,7,487,12,37,407,83,105,Rendah
28,GORONTALO,220,15,1406,38,11,876,43,493,Rendah
29,SULAWESI BARAT,46,12,537,10,24,821,185,285,Rendah
30,MALUKU,119,15,666,205,25,751,113,299,Rendah
31,MALUKU UTARA,98,23,210,20,2,125,84,45,Rendah
32,PAPUA BARAT,39,13,704,129,171,1365,81,431,Rendah
33,PAPUA,103,43,1370,238,313,3929,29,540,Rendah

In [36]:
df_2019.to_excel('2019_FINAL.xlsx',index=False)

2020

In [37]:
df_2020 = pd.read_excel('2020+_cluster.xlsx')
provinsi = df_2020['Provinsi']
df_2020 = df_2020.drop(columns=['Provinsi','tingkat kriminalitas','jumlah kejahatan','Risiko Terkena Kejahatan '])

In [38]:
df_2020.head()

,kejahatan terhadap kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan
0,267,26,28,2504,140,1582,1120,1256
1,216,104,105,8693,685,6201,4904,4817
2,333,16,104,6278,277,806,1352,1988
3,118,19,8,1969,254,1671,987,918
4,69,15,31,2870,160,407,1206,739

In [39]:
kmeans = KMeans(n_clusters=3,random_state=144)
kmeans.fit(df_2020)

c:\Users\shiro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=144)

In [40]:
labels = kmeans.labels_

In [41]:
from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(df_2020,labels)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.4517230648371151

In [42]:
df_2020['cluster'] = labels
df_2020.head()

,kejahatan terhadap kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan,cluster
0,267,26,28,2504,140,1582,1120,1256,2
1,216,104,105,8693,685,6201,4904,4817,1
2,333,16,104,6278,277,806,1352,1988,2
3,118,19,8,1969,254,1671,987,918,0
4,69,15,31,2870,160,407,1206,739,2

In [43]:
df_2020_0 = df_2020.loc[df_2020['cluster']==0]
df_2020_1 = df_2020.loc[df_2020['cluster']==1]
df_2020_2 = df_2020.loc[df_2020['cluster']==2]

0

In [44]:
df_2020_0.describe().mean().mean()

309.79625951977437

In [45]:
df_2020_1.describe().mean().mean()

1780.710754621713

In [46]:
df_2020_2.describe().mean().mean()

770.6407058551516

0 = Rendah

1 = Tinggi

2 = Sedang

In [47]:
tingkat_kriminalitas_bin=[]
for i in df_2020['cluster']:
    if i == 0 :
        tingkat_kriminalitas_bin.append('Rendah')
    elif i == 1 :
        tingkat_kriminalitas_bin.append('Tinggi')
    else:
        tingkat_kriminalitas_bin.append('Sedang')

In [48]:
df_2020['cluster'] = tingkat_kriminalitas_bin
df_2020 = df_2020.rename(columns={'cluster': 'Tingkat Kriminalitas'})

df_2020.insert(0, 'Provinsi',provinsi)
df_2020

,Provinsi,kejahatan terhadap kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhdap hak milik,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan,Tingkat Kriminalitas
0,ACEH,267,26,28,2504,140,1582,1120,1256,Sedang
1,SUMATERA UTARA,216,104,105,8693,685,6201,4904,4817,Tinggi
2,SUMATERA BARAT,333,16,104,6278,277,806,1352,1988,Sedang
3,RIAU,118,19,8,1969,254,1671,987,918,Rendah
4,JAMBI,69,15,31,2870,160,407,1206,739,Sedang
5,SUMATERA SELATAN,371,136,152,3548,723,1621,1989,1708,Sedang
6,BENGKULU,98,24,6,1122,89,206,486,399,Rendah
7,LAMPUNG,307,20,42,2836,568,1771,1297,627,Sedang
8,KEP. BANGKA BELITUNG,38,8,50,717,41,328,158,165,Rendah
9,KEP. RIAU,129,9,1,1337,107,360,564,576,Rendah
10,DKI JAKARTA,120,36,18,3307,295,6338,5115,1331,Tinggi
11,JAWA BARAT,465,32,13,3421,214,1013,3214,1814,Sedang
12,JAWA TENGAH,227,34,233,4265,193,1415,1488,623,Sedang
13,DI YOGYAKARTA,48,7,17,1715,111,283,853,456,Rendah
14,JAWA TIMUR,227,65,211,6929,543,3640,4102,2303,Tinggi
15,BANTEN,72,12,114,1366,82,584,510,282,Rendah
16,BALI,82,5,11,1195,68,777,382,607,Rendah
17,NUSA TENGGARA BARAT,41,5,51,1763,319,288,677,452,Rendah
18,NUSA TENGGARA TIMUR,229,62,11,1849,83,2,739,2408,Rendah
19,KALIMANTAN BARAT,144,20,99,1727,74,721,417,163,Rendah
20,KALIMANTAN TENGAH,57,28,2,715,114,646,262,221,Rendah
21,KALIMANTAN SELATAN,45,33,0,1286,320,1726,403,398,Rendah
22,KALIMANTAN TIMUR,105,13,0,1114,170,1677,371,524,Rendah
23,KALIMANTAN UTARA,35,1,9,346,24,200,61,108,Rendah
24,SULAWESI UTARA,263,50,46,1387,66,145,1075,2359,Rendah
25,SULAWESI TENGAH,211,17,38,2608,112,319,901,1484,Sedang
26,SULAWESI SELATAN,371,50,399,5605,577,1208,2459,1708,Sedang
27,SULAWESI TENGGARA,95,13,6,395,16,45,147,663,Rendah
28,GORONTALO,145,17,53,698,53,93,386,1203,Rendah
29,SULAWESI BARAT,59,12,10,864,29,121,282,579,Rendah
30,MALUKU,182,10,97,997,18,124,327,891,Rendah
31,MALUKU UTARA,114,3,9,101,6,89,49,174,Rendah
32,PAPUA BARAT,33,10,111,1156,1156,45,393,669,Rendah
33,PAPUA,119,52,218,3769,578,26,644,1413,Sedang

In [49]:
df_2020.to_excel('2020_FINAL.xlsx',index=False)

2021

In [50]:
df_2021 = pd.read_excel('2021.xlsx')
provinsi = df_2021['Provinsi']

In [51]:
df_2021 = df_2021.drop(columns=['Provinsi','crime total','tingkat risiko'])

In [52]:
kmeans = KMeans(n_clusters=3,random_state=144)
kmeans.fit(df_2021)

c:\Users\shiro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=144)

In [53]:
labels = kmeans.labels_

In [54]:
from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(df_2021,labels)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.4856636760722934

In [55]:
df_2021['cluster'] = labels
df_2021.head()

,Kejahatan nyawa,kejahatan fisik,kejahatan kesusilaan,kejahatan kemerdekaan orang,kejahatan hak milik dengan kekerasan,kejahatan hak milik tanpa kekerasan,kejahatan narkotika,"kejahatan penipuan, korupsi",cluster
0,15,1206,232,29,145,2408,1596,1130,2
1,71,6207,774,55,780,10916,5932,5562,1
2,20,1724,294,97,185,3732,913,989,2
3,21,1013,143,11,413,3152,1646,1095,2
4,11,531,69,9,87,1770,619,767,0

In [56]:
df_2021_0 = df_2021.loc[df_2021['cluster']==0]
df_2021_1 = df_2021.loc[df_2021['cluster']==1]
df_2021_2 = df_2021.loc[df_2021['cluster']==2]

In [57]:
df_2021_0.describe().mean().mean()

314.3274148696755

In [58]:
df_2021_1.describe().mean().mean()

2885.6666666666665

In [59]:
df_2021_2.describe().mean().mean()

898.5364892770658

0 = Rendah

1 = Tinggi

2 = Sedang

In [60]:
tingkat_kriminalitas_bin=[]
for i in df_2021['cluster']:
    if i == 0 :
        tingkat_kriminalitas_bin.append('Rendah')
    elif i == 1 :
        tingkat_kriminalitas_bin.append('Tinggi')
    else:
        tingkat_kriminalitas_bin.append('Sedang')

In [61]:
df_2021['cluster'] = tingkat_kriminalitas_bin
df_2021 = df_2021.rename(columns={'cluster': 'Tingkat Kriminalitas'})

df_2021.insert(0, 'Provinsi',provinsi)
df_2021

,Provinsi,Kejahatan nyawa,kejahatan fisik,kejahatan kesusilaan,kejahatan kemerdekaan orang,kejahatan hak milik dengan kekerasan,kejahatan hak milik tanpa kekerasan,kejahatan narkotika,"kejahatan penipuan, korupsi",Tingkat Kriminalitas
0,ACEH,15,1206,232,29,145,2408,1596,1130,Sedang
1,SUMATERA UTARA,71,6207,774,55,780,10916,5932,5562,Tinggi
2,SUMATERA BARAT,20,1724,294,97,185,3732,913,989,Sedang
3,RIAU,21,1013,143,11,413,3152,1646,1095,Sedang
4,JAMBI,11,531,69,9,87,1770,619,767,Rendah
5,SUMATERA SELATAN,71,1551,172,141,563,2911,2554,1766,Sedang
6,BENGKULU,33,479,108,1,106,963,340,556,Rendah
7,LAMPUNG,21,647,247,41,399,2532,1521,1373,Sedang
8,KEP. BANGKA BELITUNG,10,150,52,47,42,690,332,130,Rendah
9,KEP. RIAU,13,514,109,1,103,1003,362,543,Rendah
10,DKI JAKARTA,32,1449,113,31,259,3153,5981,4595,Sedang
11,JAWA BARAT,20,1445,371,11,257,2950,1141,2792,Sedang
12,JAWA TENGAH,30,382,349,11,236,3883,1601,1814,Sedang
13,DI YOGYAKARTA,6,573,98,27,126,1769,460,1225,Rendah
14,JAWA TIMUR,55,1404,256,177,341,4976,2629,2817,Sedang
15,BANTEN,8,521,81,151,94,1657,634,718,Rendah
16,BALI,6,414,65,4,54,821,668,408,Rendah
17,NUSA TENGGARA BARAT,11,646,95,46,284,2120,571,876,Rendah
18,NUSA TENGGARA TIMUR,40,1726,160,14,42,1494,41,574,Rendah
19,KALIMANTAN BARAT,35,184,137,112,54,1254,755,431,Rendah
20,KALIMANTAN TENGAH,17,305,115,1,86,837,590,315,Rendah
21,KALIMANTAN SELATAN,38,462,51,0,367,1208,1582,539,Rendah
22,KALIMANTAN TIMUR,12,352,113,1,151,862,1354,356,Rendah
23,KALIMANTAN UTARA,10,91,32,10,19,340,245,72,Rendah
24,SULAWESI UTARA,74,1976,774,88,72,1394,100,945,Rendah
25,SULAWESI TENGAH,18,1391,175,22,140,2121,340,677,Rendah
26,SULAWESI SELATAN,71,3848,208,311,348,4428,1013,1786,Sedang
27,SULAWESI TENGGARA,26,734,173,9,42,632,192,122,Rendah
28,GORONTALO,13,1043,129,73,4,696,101,467,Rendah
29,SULAWESI BARAT,8,505,64,7,15,607,175,244,Rendah
30,MALUKU,10,993,1398,119,23,894,142,307,Rendah
31,MALUKU UTARA,1,255,100,13,14,112,120,49,Rendah
32,PAPUA BARAT,10,655,47,124,155,1301,120,356,Rendah
33,PAPUA,27,1296,100,176,532,3678,241,701,Sedang

In [62]:
df_2021.to_excel('2021_FINAL.xlsx',index=False)

2022

In [63]:
df_2022 = pd.read_excel('2022.xlsx')
provinsi = df_2022['Provinsi']

In [64]:
df_2022.columns

Index(['Provinsi', 'kejahatan (crime total) yang dilaporkan ',
       'Tingkat Risiko Terkena Kejahatan ', 'Kejahatan Terhadap Kesusilaan',
       'kejahatan terhadap nyawa', 'kejahatan terhadap kemerdekaan',
       'kejahatan terhadap hak milik tanpa kekerasan',
       'kejahatan terhadap hak milik dengan kekerasan',
       'kejahatan terkait narkotika',
       'kejahatan penipuan, penggelapan, dan korupsi',
       'kejahatan terhadap fisik/badan', 'Unnamed: 11'],
      dtype='object')

In [65]:
df_2022 = df_2022.drop(columns=[
    'Provinsi','kejahatan (crime total) yang dilaporkan ',
    'Tingkat Risiko Terkena Kejahatan ','Unnamed: 11'
    ])

In [66]:
df_2022

,Kejahatan Terhadap Kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhadap hak milik tanpa kekerasan,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan
0,204,29,23,2380,107,1208,1023,1074
1,904,96,86,12433,540,5949,5396,4287
2,340,10,48,1971,98,994,739,1299
3,41,24,5,2622,255,1670,946,782
4,46,15,3,1545,73,361,597,390
5,89,69,107,2916,564,4055,1768,1235
6,112,36,2,1032,85,350,561,420
7,275,22,78,3056,431,1683,1778,311
8,21,8,31,543,23,330,110,123
9,129,16,52,864,63,236,533,448
10,178,77,11,3908,346,5810,5439,1619
11,293,29,9,2141,159,757,1980,1095
12,420,48,6,2889,188,1673,1326,295
13,48,4,13,964,55,312,803,352
14,308,53,110,6634,404,2873,3497,1716
15,93,4,77,1140,78,565,700,449
16,60,6,7,792,34,696,320,312
17,58,5,25,1490,197,315,478,414
18,216,44,63,1106,35,2,495,1322
19,108,21,135,1398,38,880,464,136
20,79,14,2,752,20,620,316,262
21,65,54,2,1124,149,1442,572,475
22,116,28,1,963,47,2066,271,289
23,20,4,12,385,11,287,55,24
24,150,58,91,1227,20,95,852,1009
25,306,17,52,1930,71,422,683,1264
26,302,44,375,4767,261,399,1729,3096
27,237,20,3,575,31,174,122,700
28,167,11,22,554,1,45,314,969
29,59,9,2,437,11,200,178,273
30,192,13,70,651,5,143,244,330
31,106,28,3,92,5,143,40,77
32,62,8,85,1045,114,13,307,492
33,101,31,148,3021,319,186,457,734

In [67]:
kmeans = KMeans(n_clusters=3,random_state=144)
kmeans.fit(df_2022)

c:\Users\shiro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=144)

In [68]:
labels = kmeans.labels_

In [69]:
from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(df_2022,labels)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.6340530831736044

In [70]:
df_2022['cluster'] = labels
df_2022.head()

,Kejahatan Terhadap Kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhadap hak milik tanpa kekerasan,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan,cluster
0,204,29,23,2380,107,1208,1023,1074,0
1,904,96,86,12433,540,5949,5396,4287,2
2,340,10,48,1971,98,994,739,1299,0
3,41,24,5,2622,255,1670,946,782,0
4,46,15,3,1545,73,361,597,390,0

In [71]:
df_2022_0 = df_2022.loc[df_2022['cluster']==0]
df_2022_1 = df_2022.loc[df_2022['cluster']==1]
df_2022_2 = df_2022.loc[df_2022['cluster']==2]

In [72]:
df_2022_0.describe().mean().mean()

344.7360667276974

In [73]:
df_2022_1.describe().mean().mean()

1236.1984851914287

In [74]:
df_2022_2.describe().mean().mean()

2828.047619047619

0 = Rendah

1 = Sedang

2 = Tinggi

In [75]:
tingkat_kriminalitas_bin=[]
for i in df_2022['cluster']:
    if i == 0 :
        tingkat_kriminalitas_bin.append('Rendah')
    elif i == 1 :
        tingkat_kriminalitas_bin.append('Sedang')
    else:
        tingkat_kriminalitas_bin.append('Tinggi')

In [76]:
df_2022['cluster'] = tingkat_kriminalitas_bin
df_2022 = df_2022.rename(columns={'cluster': 'Tingkat Kriminalitas'})

df_2022.insert(0, 'Provinsi',provinsi)
df_2022

,Provinsi,Kejahatan Terhadap Kesusilaan,kejahatan terhadap nyawa,kejahatan terhadap kemerdekaan,kejahatan terhadap hak milik tanpa kekerasan,kejahatan terhadap hak milik dengan kekerasan,kejahatan terkait narkotika,"kejahatan penipuan, penggelapan, dan korupsi",kejahatan terhadap fisik/badan,Tingkat Kriminalitas
0,ACEH,204,29,23,2380,107,1208,1023,1074,Rendah
1,SUMATERA UTARA,904,96,86,12433,540,5949,5396,4287,Tinggi
2,SUMATERA BARAT,340,10,48,1971,98,994,739,1299,Rendah
3,RIAU,41,24,5,2622,255,1670,946,782,Rendah
4,JAMBI,46,15,3,1545,73,361,597,390,Rendah
5,SUMATERA SELATAN,89,69,107,2916,564,4055,1768,1235,Sedang
6,BENGKULU,112,36,2,1032,85,350,561,420,Rendah
7,LAMPUNG,275,22,78,3056,431,1683,1778,311,Rendah
8,KEP BANGKA BELITUNG,21,8,31,543,23,330,110,123,Rendah
9,KEP RIAU,129,16,52,864,63,236,533,448,Rendah
10,DKI JAKARTA,178,77,11,3908,346,5810,5439,1619,Sedang
11,JAWA BARAT,293,29,9,2141,159,757,1980,1095,Rendah
12,JAWA TENGAH,420,48,6,2889,188,1673,1326,295,Rendah
13,DI YOGYAKARTA,48,4,13,964,55,312,803,352,Rendah
14,JAWA TIMUR,308,53,110,6634,404,2873,3497,1716,Sedang
15,BANTEN,93,4,77,1140,78,565,700,449,Rendah
16,BALI,60,6,7,792,34,696,320,312,Rendah
17,NUSA TENGGARA BARAT,58,5,25,1490,197,315,478,414,Rendah
18,NUSA TENGGARA TIMUR,216,44,63,1106,35,2,495,1322,Rendah
19,KALIMANTAN BARAT,108,21,135,1398,38,880,464,136,Rendah
20,KALIMANTAN TENGAH,79,14,2,752,20,620,316,262,Rendah
21,KALIMANTAN SELATAN,65,54,2,1124,149,1442,572,475,Rendah
22,KALIMANTAN TIMUR,116,28,1,963,47,2066,271,289,Rendah
23,KALIMANTAN UTARA,20,4,12,385,11,287,55,24,Rendah
24,SULAWESI UTARA,150,58,91,1227,20,95,852,1009,Rendah
25,SULAWESI TENGAH,306,17,52,1930,71,422,683,1264,Rendah
26,SULAWESI SELATAN,302,44,375,4767,261,399,1729,3096,Sedang
27,SULAWESI TENGGARA,237,20,3,575,31,174,122,700,Rendah
28,GORONTALO,167,11,22,554,1,45,314,969,Rendah
29,SULAWESI BARAT,59,9,2,437,11,200,178,273,Rendah
30,MALUKU,192,13,70,651,5,143,244,330,Rendah
31,MALUKU UTARA,106,28,3,92,5,143,40,77,Rendah
32,PAPUA BARAT,62,8,85,1045,114,13,307,492,Rendah
33,PAPUA,101,31,148,3021,319,186,457,734,Rendah

In [77]:
df_2022.to_excel('2022_FINAL.xlsx',index=False)

In [78]:
df1 = pd.read_excel('2018_cluster.xlsx')

In [79]:
tingkat_kriminalitas_bin=[]
for i in df1['tingkat kriminalitas']:
    if i == "Rendah" :
        tingkat_kriminalitas_bin.append(0)
    elif i == "Sedang" :
        tingkat_kriminalitas_bin.append(1)
    else:
        tingkat_kriminalitas_bin.append(2)